# Generated by Django 3.2.3 on 2021-06-14 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='num',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
